### ISSUE TITLE
Doest power on/off

### ISSUE THREAD

**Issue by roadglide03** [jpansarasa/SmartThings#1]
I have a gen5 Aeotech Heavy Duty Switch.  I tried your code but it doesn't power on?

**Comment by jpansarasa** [comment]
What do you mean by power on? You should be able to turn on and off the switch at the device using a button under the cover panel. If that works, it could be the configuration of the device in SmartThings.

By default, the On/Off functionality is disabled. If you go into the preferences for the device (the gear icon in the phone app) and ensure that the "Disable On/Off" is on the off position.

**Comment by roadglide03** [comment]
Yes that works fine but can't form the smarthings app.  It shows up but doesn't do anything.  Ok I will take a look at what you are suggesting thanks for the quick reply.

**Comment by roadglide03** [comment]
Ok just looked on/off shows enabled.  Any other ideas?

**Comment by jpansarasa** [comment]
It is hard to do this remotely but please bear with me.
Try setting the other way and try it again.

**Comment by roadglide03** [comment]
Same thing and I restarted the hub.  The red light is not blinking but I am not sure of another way to check connection status.  I don't trust what My Devices states it seems to default to active?

I have a dumb question int he smarthings guide it stated the "device network id" can be what you want.  This doesn't make sense shouldn't each z-wave device have a unique id otherwise how does it find it?  I could have a few of these I am thinking this may be the issue let me know if I am crazy, thanks Andy

**Comment by jpansarasa** [comment]
Andy,

I am not sure what is going on. If you don't mind, could you try removing the device and adding it back?
I have added some links with descriptions on how to do this (just in case):
- [Removing and excluding a device that is already connected](https://support.smartthings.com/hc/en-us/articles/200878314-How-do-I-exclude-a-Z-Wave-device-using-SmartThings-)
- [Add the device handler in the IDE](http://docs.smartthings.com/en/latest/device-type-developers-guide/quick-start.html)
- [How to connect and configure new devices](https://support.smartthings.com/hc/en-us/articles/205956950-How-to-connect-and-configure-new-devices)

Thanks,
James

**Comment by roadglide03** [comment]
I have done this a couple times but can try again.  Where does the device network I'd com from?   Expected it to be on the device but I don't see it?

**Comment by jpansarasa** [comment]
I have never set a device network ID. That is set when the device joins the network. You can not add a device using the web site, only through the phone app. If you are trying to add a device using the "new device" button on the web site, it won't work.

**Comment by roadglide03** [comment]
Its interesting if I add the device handler then add it via the phone app it finds a "Aeon Secure Smart Energy Switch UK" I can't power/off but I can see Wattage usage.  If I change the device to your script nothing works.  I sent Aeon an email not sure if its the device or what?

**Comment by jpansarasa** [comment]
If you switch to my device type, I have an "Enable debug" configuration option. That dumps some _possibly_ useful information in the [logs](https://graph.api.smartthings.com/ide/logs) section of the IDE.

I understand that this is frustrating. I have a hard time debugging this type of problem as well.

**Comment by roadglide03** [comment]
Aeon contacted me and provided your script I can see wattage when I power on manually but I can power on and off still.  I have disable on/off (off) and switch all is set to on/off.  I also tried opposite settings.  I enabled logs but all it says is waiting for events. I do see on/off events when I press the button on the switch so it see I am power cycling physically.  

When I add this via the App on iPhone it recognizes a Aeon UK Switch not yours is there a way to search for that?  or do I just change the type on the website?

**Comment by roadglide03** [comment]
Heres the events:

2017-02-17 8:05:49.744 AM EST
moments ago	DEVICE		power	0		Garage heater power is 0 W
2017-02-17 8:05:34.783 AM EST
moments ago	DEVICE		power	5041		Garage heater power is 5041 W
2017-02-17 8:05:29.808 AM EST
moments ago	DEVICE		power	2352		Garage heater power is 2352 W
2017-02-17 8:05:15.462 AM EST
moments ago	DEVICE physical		switch	off		Garage heater switch is off
2017-02-17 8:05:14.748 AM EST
moments ago	DEVICE		power	0		Garage heater power is 0 W
2017-02-17 8:05:05.355 AM EST
moments ago	DEVICE physical		switch	on		Garage heater switch is on
2017-02-17 8:04:59.766 AM EST
moments ago	DEVICE		power	5108		Garage heater power is 5108 W

**Comment by jpansarasa** [comment]
Once the device is connected to the network, you can change the device type it uses in the IDE.

1. Go to the (Device List)[https://graph.api.smartthings.com/device/list]
2. Click on the link for the device you want to change
3. At the bottom of the page, select the '**Edit**' button
4. In the '**Type**' drop down list box, select 'Aeon Labs Heavy Duty Smart Energy Switch'
5. Then edit the device type on the phone (it may take a while to synchronize), and set the 'Enable debug logging?' switch

You should see better logging messages in the IDE.

**Comment by roadglide03** [comment]
Yep that's what I did but not getting anything helpful

**Comment by jpansarasa** [comment]
Are you seeing the debug messages?
If you aren't, then something else is wrong.
If you are, then maybe the device is defective.

**Comment by roadglide03** [comment]
Yea the only time I see anything in the logs is when I manually press the on button on the device.

**Comment by roadglide03** [comment]
Ok so I bought an Aeon Z-Stick and it works through that but not on Smarthings I can power on/off still with smarthings.  I tested using incontrol software (now axial) using the z-wave stick.  So its not the device.

**Comment by jpansarasa** [comment]
For some reason, it seems like you are never running my device type code.
If you are not seeing the debug messages that match the ones in my device type code, the device type is configured incorrectly in SmartThings.

I am not sure how to help at this point.

**Comment by roadglide03** [comment]
Here are the messages I removed it from the z-wave stick and added it back in to Smarthtings. It is using your device handler:


Date	Source	Type	Name	Value	User	Displayed Text
2017-02-21 9:04:22.686 AM EST
moments ago	COMMAND			off		off command was sent to Garage Heater
2017-02-21 9:04:14.769 AM EST
moments ago	COMMAND			on		on command was sent to Garage Heater
2017-02-21 9:03:29.476 AM EST
moments ago	COMMAND			off		off command was sent to Garage Heater
2017-02-21 9:03:19.237 AM EST
moments ago	COMMAND			on		on command was sent to Garage Heater
2017-02-21 9:03:15.123 AM EST
moments ago	COMMAND			off		off command was sent to Garage Heater
2017-02-21 9:03:08.289 AM EST
moments ago	DEVICE	ENTITY_UPDATE	DeviceUpdated			Device '{{ deviceName }}' updated
2017-02-21 9:02:14.453 AM EST
moments ago	DEVICE		energy	0.090		Garage Heater energy is 0.090 kWh
2017-02-21 9:02:00.618 AM EST
moments ago	DEVICE	ENTITY_UPDATE	DeviceUpdated			Device '{{ deviceName }}' updated
2017-02-21 9:00:59.326 AM EST
moments ago	DEVICE		power	0		Aeon Secure Smart Energy Switch UK power is 0 W
2017-02-21 9:00:54.653 AM EST
moments ago	COMMAND			on		on command was sent to Aeon Secure Smart Energy Switch UK
2017-02-21 9:00:52.709 AM EST
moments ago	COMMAND			off		off command was sent to Aeon Secure Smart Energy Switch UK
2017-02-21 9:00:50.564 AM EST
moments ago	DEVICE	ENTITY_UPDATE	DeviceUpdated			Device '{{ deviceName }}' updated
2017-02-21 9:00:48.036 AM EST
moments ago	DEVICE physical		switch	on		Aeon Secure Smart Energy Switch UK switch is on
2017-02-21 9:00:23.679 AM EST
moments ago	DEVICE	ENTITY_UPDATE	DeviceCreated			Device '{{ deviceName }}' created
2017-02-21 9:00:23.493 AM EST
moments ago	COMMAND			configure		configure command was sent to Aeon Secure Smart Energy Switch UK

**Comment by roadglide03** [comment]
Preferences (edit)	
Name	Type	Value
debugOutput	boolean	true
disableOnOff	boolean	false
displayEvents	boolean	true
reportInterval	number	5
switchAll	enum	On And Off Enabled

**Comment by jpansarasa** [comment]
If you are seeing "Aeon Secure Smart Energy Switch UK", you are not running my device type.

**Comment by jpansarasa** [comment]
I just realized that I am using an old hub. This maybe an issue with the device type and the new hub.

**Comment by roadglide03** [comment]
I have your device handler in play it shows up int he pull down.  What I did is when the UK switch came up I saved it then I went into the device handler and switched the script to yours.  Not sure what else to do?  The UK and HD switch must use the same device type?  The UK version doesn't work either.  Let me know what I need to change?  thanks Andy

**Comment by roadglide03** [comment]
I don't think its your script I think its the hub.  I just installed a z-wave lock it supports and although I see it, it will not lock or unlock I am sending the hub back and going with something else.  thanks for your help Andy

**Comment by jpansarasa** [comment]
That sucks. Sorry I could not help.

**Comment by roadglide03** [comment]
It was the hub
